### ISSUE TITLE
Make [[docstring-links]] into links

### ISSUE THREAD

**Issue by escherize** [clj-commons/marginalia#181] opened 2023-10-19 15:55 UTC
People write links like [[this-var]] into docstrings. It would be fantastic if we could make those links.  This probably requires having ids on elements as described in #155.

**Comment by tsmacdonald** [comment] 2023-11-05 13:24
Duplicate of #157.

This is on my personal shortlist of things I want soon, but as mentioned needs #155.

I have some questions about ns resolution, but I'll see how things go

**Closed by tsmacdonald** 2023-11-05 13:24 UTC
